name: automerge
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: astral-sh/setup-uv@v6
              name: Setup uv
              with:
                enable-cache: true
            - name: Setup Python virtual environment
              run: uv venv --seed
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Dev Chrome
              run: npm run dev
            - name: Dev Firefox
              run: npm run dev:ff
