name: test-ci
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
            - uses: nick-fields/retry@v3
              with:
                timeout_minutes: 20
                max_attempts: 2
                retry_on: error
                command: npm install &&npm run test-ci

    test-storage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
            - uses: nick-fields/retry@v3
              with:
                timeout_minutes: 20
                max_attempts: 2
                retry_on: error
                command: npm install &&npm run test-storage
            - uses: actions/upload-artifact@v4
              with:
                name: test-storage-screenshots
                path: ./tmp/*.jpg
                if-no-files-found: ignore
                retention-days: 7
                compression-level: 3



